#!/usr/bin/env python3
"""Embed the SVG assets the web app draws inline into webapp/CastRecruiter.html.

Apps Script has no static asset hosting, so an SVG the page uses has to live in the
page itself. Each asset becomes a <symbol> in one hidden sprite, drawn with
<svg><use href="#id"/></svg>. Re-run this after changing any asset below; it rewrites
only the block between the SPRITE_START / SPRITE_END markers.

Pasting the exported files in by hand breaks in two quiet ways, which is why this exists:
  * The Affinity exports all reuse the same internal ids (`_clip1`), and ids are
    document-global, so every icon would clip against the first icon's clip path.
    Every id is prefixed with its symbol id here.
  * The Maleperduis logo carries a <style> with `.cls-1 { fill: #fff }`. Inlined, that
    rule applies to the whole page. It is dropped and the fill set on each shape.

Colours are swapped for CSS so the page, not the asset, decides them:
  * the brand gold in the icons  -> currentColor (the icon takes its text's colour)
  * the dark cut-out in the Solid dice -> var(--icon-cutout-colour)
  * the logo's white              -> currentColor

    python3 dextrous/build_svg_sprite.py
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HTML = REPO / "webapp" / "CastRecruiter.html"
DICE = REPO / "assets" / "inline icons" / "dice"
BRANDING = REPO / "assets" / "branding"

SPRITE_START = "<!-- SPRITE_START: generated by dextrous/build_svg_sprite.py - do not hand-edit -->"
SPRITE_END = "<!-- SPRITE_END -->"

# Brand gold as exported (two near-identical golds across the icon sets), and the
# Solid dice's cut-out, which is the page ground.
COLOUR_SWAPS = {
    "rgb(229,184,127)": "currentColor",
    "rgb(222,186,135)": "currentColor",
    "rgb(0,18,18)": "var(--icon-cutout-colour)",
}

# (symbol id, source file). The files spell Solid as "Soild".
ASSETS: list[tuple[str, Path]] = [
    *[
        (f"icon-dice-{style}-{shape.lower()}", DICE / f"{label} {shape}.svg")
        for style, label in (("solid", "Soild"), ("void", "Void"))
        for shape in ("Circle", "Null", "Square", "Triangle")
    ],
    ("maleperduis-logo", BRANDING / "Horizontal_Duotone_White.svg"),
]


def to_symbol(symbol_id: str, source: str) -> str:
    svg = re.sub(r"<\?xml.*?\?>|<!DOCTYPE.*?>", "", source, flags=re.S)

    root = re.search(r"<svg\b[^>]*>", svg)
    view_box = re.search(r'viewBox="([^"]+)"', root.group(0))
    if not view_box:
        raise ValueError(f"{symbol_id}: root <svg> has no viewBox")
    svg = svg[: root.start()] + f'<symbol id="{symbol_id}" viewBox="{view_box.group(1)}">' + svg[root.end():]
    svg = svg.replace("</svg>", "</symbol>")

    # A <style> would leak page-wide; turn its single fill class into attributes.
    class_fills = dict(re.findall(r"\.([\w-]+)\s*\{\s*fill:\s*([^;}]+);?\s*\}", svg))
    svg = re.sub(r"<defs>.*?</defs>", "", svg, flags=re.S)
    for cls, fill in class_fills.items():
        fill = "currentColor" if fill.strip().lower() in ("#fff", "#ffffff", "white") else fill.strip()
        svg = svg.replace(f'class="{cls}"', f'fill="{fill}"')

    svg = re.sub(r'\s(?:affinity:id|data-name)="[^"]*"', "", svg)

    for old_id in re.findall(r'\sid="([^"]+)"', svg):
        if old_id == symbol_id:
            continue
        new_id = f"{symbol_id}--{re.sub(r'[^A-Za-z0-9_-]', '-', old_id)}"
        svg = svg.replace(f'id="{old_id}"', f'id="{new_id}"')
        svg = svg.replace(f"url(#{old_id})", f"url(#{new_id})")
        svg = svg.replace(f'href="#{old_id}"', f'href="#{new_id}"')

    for old, new in COLOUR_SWAPS.items():
        svg = svg.replace(old, new)
    leftover = set(re.findall(r"rgb\([^)]*\)|#[0-9a-fA-F]{3,6}\b", svg))
    if leftover:
        raise ValueError(f"{symbol_id}: unmapped colours {sorted(leftover)} - add them to COLOUR_SWAPS")

    return "\n".join("    " + line.strip() for line in svg.strip().splitlines() if line.strip())


def main() -> int:
    symbols = []
    for symbol_id, path in ASSETS:
        if not path.exists():
            print(f"FAILED — missing asset {path.relative_to(REPO)}", file=sys.stderr)
            return 1
        symbols.append(to_symbol(symbol_id, path.read_text(encoding="utf-8")))

    block = "\n".join([
        SPRITE_START,
        '<svg width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute" '
        'xmlns="http://www.w3.org/2000/svg">',
        *symbols,
        "</svg>",
        SPRITE_END,
    ])
    ET.fromstring(block[block.index("<svg"): block.rindex("</svg>") + len("</svg>")])  # well-formed or raise

    html = HTML.read_text(encoding="utf-8")
    if SPRITE_START in html:
        start = html.index(SPRITE_START)
        end = html.index(SPRITE_END, start) + len(SPRITE_END)
        html = html[:start] + block + html[end:]
    else:
        anchor = "</body>"
        if html.count(anchor) != 1:
            print("FAILED — expected exactly one </body> in the HTML", file=sys.stderr)
            return 1
        html = html.replace(anchor, block + "\n" + anchor)
    HTML.write_text(html, encoding="utf-8")

    ids = sorted(re.findall(r'\sid="([^"]+)"', html))
    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    if duplicates:
        print(f"FAILED — duplicate ids in the page: {duplicates}", file=sys.stderr)
        return 1

    print(f"Embedded {len(symbols)} symbols ({len(block) / 1024:.1f} KB) into {HTML.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
